// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: cryptovotepb/go_grpc_cryptovote.proto

package cryptovotepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The EmptyReq message containing the CryptoVote data.
type EmptyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_cryptovotepb_go_grpc_cryptovote_proto_rawDescGZIP(), []int{0}
}

// The CryptoVote message containing the CryptoVote data.
type CryptoVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crypto      *CryptoCurrency `protobuf:"bytes,1,opt,name=crypto,proto3" json:"crypto,omitempty"`
	QtdUpvote   int32           `protobuf:"varint,2,opt,name=qtd_upvote,json=qtdUpvote,proto3" json:"qtd_upvote,omitempty"`
	QtdDownvote int32           `protobuf:"varint,3,opt,name=qtd_downvote,json=qtdDownvote,proto3" json:"qtd_downvote,omitempty"`
	IdHex       string          `protobuf:"bytes,4,opt,name=idHex,proto3" json:"idHex,omitempty"`
}

func (x *CryptoVote) Reset() {
	*x = CryptoVote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CryptoVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoVote) ProtoMessage() {}

func (x *CryptoVote) ProtoReflect() protoreflect.Message {
	mi := &file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoVote.ProtoReflect.Descriptor instead.
func (*CryptoVote) Descriptor() ([]byte, []int) {
	return file_cryptovotepb_go_grpc_cryptovote_proto_rawDescGZIP(), []int{1}
}

func (x *CryptoVote) GetCrypto() *CryptoCurrency {
	if x != nil {
		return x.Crypto
	}
	return nil
}

func (x *CryptoVote) GetQtdUpvote() int32 {
	if x != nil {
		return x.QtdUpvote
	}
	return 0
}

func (x *CryptoVote) GetQtdDownvote() int32 {
	if x != nil {
		return x.QtdDownvote
	}
	return 0
}

func (x *CryptoVote) GetIdHex() string {
	if x != nil {
		return x.IdHex
	}
	return ""
}

// The CryptoCurrency message containing as CryptoCurrency
type CryptoCurrency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *CryptoCurrency) Reset() {
	*x = CryptoCurrency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CryptoCurrency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoCurrency) ProtoMessage() {}

func (x *CryptoCurrency) ProtoReflect() protoreflect.Message {
	mi := &file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoCurrency.ProtoReflect.Descriptor instead.
func (*CryptoCurrency) Descriptor() ([]byte, []int) {
	return file_cryptovotepb_go_grpc_cryptovote_proto_rawDescGZIP(), []int{2}
}

func (x *CryptoCurrency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CryptoCurrency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_cryptovotepb_go_grpc_cryptovote_proto protoreflect.FileDescriptor

var file_cryptovotepb_go_grpc_cryptovote_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76, 0x6f, 0x74, 0x65, 0x70, 0x62, 0x2f, 0x67,
	0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76, 0x6f, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76,
	0x6f, 0x74, 0x65, 0x70, 0x62, 0x22, 0x0a, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x22, 0x9a, 0x01, 0x0a, 0x0a, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x56, 0x6f, 0x74, 0x65,
	0x12, 0x34, 0x0a, 0x06, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76, 0x6f, 0x74, 0x65, 0x70, 0x62, 0x2e,
	0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x06,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x74, 0x64, 0x5f, 0x75, 0x70,
	0x76, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x71, 0x74, 0x64, 0x55,
	0x70, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x71, 0x74, 0x64, 0x5f, 0x64, 0x6f, 0x77,
	0x6e, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x71, 0x74, 0x64,
	0x44, 0x6f, 0x77, 0x6e, 0x76, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x64, 0x48, 0x65,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x64, 0x48, 0x65, 0x78, 0x22, 0x3c,
	0x0a, 0x0e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x32, 0x68, 0x0a, 0x11,
	0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x56, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x53, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x76, 0x6f, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76, 0x6f, 0x74,
	0x65, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x22, 0x00, 0x30, 0x01, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x69, 0x6f, 0x66, 0x6f, 0x72, 0x6d, 0x69, 0x67, 0x61,
	0x2f, 0x67, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76,
	0x6f, 0x74, 0x65, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x76, 0x6f, 0x74, 0x65, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cryptovotepb_go_grpc_cryptovote_proto_rawDescOnce sync.Once
	file_cryptovotepb_go_grpc_cryptovote_proto_rawDescData = file_cryptovotepb_go_grpc_cryptovote_proto_rawDesc
)

func file_cryptovotepb_go_grpc_cryptovote_proto_rawDescGZIP() []byte {
	file_cryptovotepb_go_grpc_cryptovote_proto_rawDescOnce.Do(func() {
		file_cryptovotepb_go_grpc_cryptovote_proto_rawDescData = protoimpl.X.CompressGZIP(file_cryptovotepb_go_grpc_cryptovote_proto_rawDescData)
	})
	return file_cryptovotepb_go_grpc_cryptovote_proto_rawDescData
}

var file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cryptovotepb_go_grpc_cryptovote_proto_goTypes = []interface{}{
	(*EmptyReq)(nil),       // 0: cryptovotepb.EmptyReq
	(*CryptoVote)(nil),     // 1: cryptovotepb.CryptoVote
	(*CryptoCurrency)(nil), // 2: cryptovotepb.CryptoCurrency
}
var file_cryptovotepb_go_grpc_cryptovote_proto_depIdxs = []int32{
	2, // 0: cryptovotepb.CryptoVote.crypto:type_name -> cryptovotepb.CryptoCurrency
	0, // 1: cryptovotepb.CryptoVoteService.ListAllCryptoCurrencies:input_type -> cryptovotepb.EmptyReq
	2, // 2: cryptovotepb.CryptoVoteService.ListAllCryptoCurrencies:output_type -> cryptovotepb.CryptoCurrency
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cryptovotepb_go_grpc_cryptovote_proto_init() }
func file_cryptovotepb_go_grpc_cryptovote_proto_init() {
	if File_cryptovotepb_go_grpc_cryptovote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CryptoVote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CryptoCurrency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cryptovotepb_go_grpc_cryptovote_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cryptovotepb_go_grpc_cryptovote_proto_goTypes,
		DependencyIndexes: file_cryptovotepb_go_grpc_cryptovote_proto_depIdxs,
		MessageInfos:      file_cryptovotepb_go_grpc_cryptovote_proto_msgTypes,
	}.Build()
	File_cryptovotepb_go_grpc_cryptovote_proto = out.File
	file_cryptovotepb_go_grpc_cryptovote_proto_rawDesc = nil
	file_cryptovotepb_go_grpc_cryptovote_proto_goTypes = nil
	file_cryptovotepb_go_grpc_cryptovote_proto_depIdxs = nil
}
